name: habit_tracker
description: "An app to track your daily habits and routines."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_heatmap_calendar: ^1.0.5
  flutter_slidable: ^4.0.0
  path_provider: ^2.1.5
  provider: ^6.1.5
  sqflite: ^2.4.2
  path: ^1.9.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
flutter:
  uses-material-design: true
  generate: true
